version: "3.8"

networks:
    app-tier:
      driver: bridge
services:
    mongo:
        image: mongo
        restart: always
        networks:
            - app-tier
    mysqldb:
        build:
            context: ./docs
        image: crudmysql
        container_name: crudmysql
        restart: always
        expose:
            - "3306"
        ports:
            - "3306:3306"
        networks:
            - app-tier
    nodeserver:
        depends_on:
            - mysqldb
            - mongo
        build:
            context: .
        command: bash -c 'while !</dev/tcp/mysqldb/3306; do sleep 1; done; nodemon server.js'
        image: crudnodejs
        container_name: crudnodejs
        volumes:
            - ./data/db:/var/lib/mysqldb
        ports:
            - "3000:3000"
        networks:
            - app-tier
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
          - "8000:80"
          - "443"
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default
          - ./nginx/default.conf:/etc/nginx/sites-available/default
          - ./nginx-conf:/etc/nginx/conf.d
        links:
          - nodeserver
          
    certbot:
        image: certbot/certbot
        container_name: certbot
        depends_on:
          - nginx
    